/* Configuration for ada_riscv_renode generated by Alire */
#ifndef ADA_RISCV_RENODE_CONFIG_H
#define ADA_RISCV_RENODE_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "ada_riscv_renode"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
